== Command Executor. [[command_executor]]

[source,java]
----
//<1>
@SagaExecutor(
        executeFor = "order-service",
        value = "OrderInitializeExecutor"
)
@RequiredArgsConstructor
public class OrderInitializeExecutor implements CommandExecutor<PlaceOrderAggregator> { //<2>

    //<3>
    @Override
    public ProcessStepManager<PlaceOrderAggregator> doProcess(
            PlaceOrderAggregator currentAggregator, //<4>
            ProcessStepManagerUtil<PlaceOrderAggregator> stepManager, //<5>
            String idempotencyKey //<6>
    ) throws
        RetryableExecutorException, //<7>
        NonRetryableExecutorException //<8>
    {
        try {
            //<9>
            //call the target endpoint by calling the service
            //update the aggregator state or accesses the data from current aggregator state
            return stepManager.next(NextExecutor.class, () -> "ORDER_INITIALIZED"); //<10>
        } catch (NetworkException e) {
            //<11>
            throw RetryableExecutorException.buildWith(e).build();
        } catch (OtherException e) {
            //<12>
            throw NonRetryableExecutorException
                                    .buildWith(e)
                                    .put("reason",e.getMessage())
                                    .put("data-1","some data")
                                    .build();
        }
    }

    @RevertBefore(startFrom = SampleSubBeforeExeInit.class) //<21>
    @RevertAfter(startFrom = SampleSubAfterExeInit.class) //<22>
    @Override //<13>
    public SagaExecutionEventName doRevert(
            //<14>
            NonRetryableExecutorException primaryExecutionException,
            //<15>
            PlaceOrderAggregator finalAggregatorState,
            //<16>
            RevertHintStore revertHintStore,
            //<17>
            String idempotencyKey
    ) throws RetryableExecutorException //<18>
    {

        {
            //Call the target endpoint by calling the service //<19>
            //Access the data from the revertHintStore
            revertHintStore.get("reason").ifPresent(value -> { //<20>
                System.out.println("value = " + value);
            });
            //use revertHintStore for adding the data to access them in subsequent compensations
            revertHintStore.put("key-1", "value-1");
            revertHintStore.put("key-2", "value-2");
        }
        return OrderStatus.CANCELED_ORDER;
    }
}
----

<1> *@SagaExecutor*: Annotate the executor with `@org.stacksaga.annotation.SagaExecutor` annotation.
The annotation provides the spring bean capabilities and also another metadata for the StackSaga framework.
+
executeFor:: The name of the target service that the executor goes to access.
value:: The bean name of the executor.
The executor is identified with this value by StackSaga engine.
After configuring the bean name, it cannot be changed at all.
If you want to the class package, it does not matter without changing the configured name.
xref:architecture:aggregator_versioning.adoc#executor_changing[See more.]

<2> *CommandExecutor<T>* IF the executor is command one, The executor should be implemented by `org.stacksaga.executor.CommandExecutor<T>`. `T` should be the target Aggregator class for the domain.

<3> Override the `doProcess()`  method and put your execution code block that should be executed when the executor is executed by the StackSaga engine.

<4> *currentAggregator*: This is the aggregator object that is initialized and passed when a request is sent to the SEC.
If the current is the first executor, the aggregator state will be identical to the object initially provided to the SEC.
The aggregator state can be modified within any executor, and the updated data will be accessible across all executors.
For example, if the aggregator is initialized with a `userId`, the same `userId` will be accessed in the first executor.
Additionally, modifications can be made to the aggregator as needed.
For instance, if the `paymentId` of the aggregator object is updated within the current executor, this updated value will be accessible in the subsequent executor.

<5> *stepManager*: This object provides the methods for giving the navigation to the engine regarding the next step.
The next step can be another executor (either a command or a query) or a process completion.
+
If we want to execute another executor after the current executor, we can use the `stepManager.next()` method or if we want to finish the LRT, we can use `stepManager.complete()` method.
For instance, after making the preAuth process if it returns `OK` response, we can go to the next executor by using the `stepManager.next()` method like below.
+
[source,java]
----
if (response.STATUS == 200) {
   return stepManager.next(StockUpdateExecutor.class, () -> "MADE_PRE_AUTH");
}
----
+
Or on the other hand, if we are in the last executor, we can use the `stepManager.complete()` method like below.
+
[source,java]
----
return stepManager.complete(OrderStatus.MADE_PAYMENT);
----

<6> *idempotencyKey*: This is the key that is provided by the SEC regarding the *specific transaction* and *specific executor* to have safe retrying with idempotency. read more about xref:architecture:idempotency.adoc[idempotency]

<7> *RetryableExecutorException*: If the executor has a *RetryableExecutorException*, it is allowed to throw it.
When a RetryableExecutorException exception is thrown, the LRT is stopped temporarily by the SEC.
See More about xref:framework:retryable_executor_exception.adoc[RetryableExecutorException]

<8> *NonRetryableExecutorException*: If the executor has a *NonRetryableExecutorException*, it is allowed to throw it.
When a `NonRetryableExecutorException` exception is thrown, the SEC stops the primary execution and starts the compensating process.


<9> By accessing necessary data from the current aggregator state, you can call the target endpoint and after that you can update the aggregator state with the received data.

<10> If there is no any error from the target endpoint, you can simply mention the next executor by using the `stepManager.next()`.
You have to pass the next executor class, and also you have to pass the event-name for the action that has been done.

<11> IF there is an error from the target endpoint, and if it is a *NetworkException* (resource unavailable error,) you can simply catch the exception and build a new xref:framework:retryable_executor_exception.adoc[RetryableExecutorException] and throw it.
While you are building the `RetryableExecutorException` you can mention the real exception that received.
+
NOTE: It is necessary to catch the resource unavailable exceptions and throw it by building a new xref:framework:retryable_executor_exception.adoc[RetryableExecutorException].
Because the SEC does not know what exceptions are presented, the resource is unavailable errors.
The exceptions that are thrown for the network related failures are different to each other based on the http client.
Therefore, SEC lets catch the error as you want and throw it by wrapping it in `RetryableExecutorException`.

<12> IF there is an error from the target endpoint, and if it is not a *NetworkException* (resource unavailable error,) you can simply catch the exception and build a new xref:framework:non_retryable_executor_exception.adoc[NonRetryableExecutorException] and throw it.
Then the SEC will stop the primary execution and start the compensating process.
While you are building the `NonRetryableExecutorException` you can mention the real exception that received and as well as you can mention any data that you want to access from the error.
For instance if you want to access the reason of the error when the compensating process, you can mention them when the `NonRetryableExecutorException` is thrown.
+
NOTE: Catching the `NonRetryableExecutorException` is not required.
If there is an error while executing the executor, the error is identified as a `NonRetryableExecutorException` by the SEC by default.
But as a best practice it is recommended to handle the `NonRetryableExecutorException` and `RetryableExecutorException` separately.
Because if you do not handle the exception separately, all the exceptions are identified as `NonRetryableExecutorException` by the SEC.

<13> Override the `doRevert()` method for invoking the compensating process.

<14> *primaryExecutionException*: `doRevert` method is called only for compensating. that means the one of primary executions was failed.
the exception that threw when the primary execution was failed is passed here as a parameter by the SEC.
it can be used to identify what was the exception, and you can access the data from the exception object that you set when the primary execution was failed.

<15> *finalAggregatorState:* This contains the final aggregator state when the `NonRetryableExecutorException` is thrown.
+
NOTE: If a `NonRetryableExecutorException` is thrown, the changes that made into the aggregator withing the same executor is not applied to the aggregator state.
Because we only execute an atomic execution withing the executor.
If that atomic executor is failed, the aggregator state should be changed.
The aggregator state should be in the state that passed from the last executor.


<16> *revertHintStore:* As we used the custom created aggregator as the payload for carrying the data into primary executions, the *RevertHintStore* is used as the payload for carrying the data into the compensating executions.
for instance, if you want to add some data after executing one compensation execution, that should be accessed by subsequent compensation executions. you can use the `revertHintStore.put(key, value)` method.

<17> *idempotencyKey*: This is the key that is provided by the SEC regarding the *specific transaction* and *specific executor* to have safe retrying with idempotency. read more about xref:architecture:idempotency.adoc[idempotency]

<18> *RetryableExecutorException:* If the `doRevert` method has a *RetryableExecutorException* (resource unavailable error,) it is allowed to throw it.
+
WARNING: any compensation execution can have only resource-unavailable errors as per the saga design pattern. you have to carefully handle the execution without any error except the resource-unavailable errors. if there is unhandled error while executing the `doRevert` method, the entire execution is terminated.
and then you have to manually handle the terminated transactions.

<19> By accessing necessary data from the current `revertHintStore`, you can call the target endpoint and after that, you can add more data to the `revertHintStore` with the received data.

<20> If the one primary execution has multiple atomic compensating executions, and it should be executed *before* the main compensating execution, you can create a `sub-before-executor` and set it with `@RevertBefore` annotation.

<21> If the one primary execution has multiple atomic compensating executions, and it should be executed *after* the main compensating execution, you can create a `sub-after-executor` and set it with `@RevertAfter` annotation.

'''
